export type {
  RadarConfig,
  RadarTarget,
  DeviceFilter,
  RadarZone,
  CreateZonePayload,
  UpdateZonePayload,
  RawRadarMessage,
  RawRadarPayload,
  CamaraActividad,
  ActividadPayload,
  TiposAlertas,
  MagosRadarPosition,
  MagosRadarTrack,
} from "./radar.types";
